# Generated by Django 4.2.11 on 2024-03-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
