# Generated by Django 4.2.11 on 2024-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0002_alter_cobranca_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='data_vencimento',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='valor',
            field=models.CharField(),
        ),
    ]
