# Generated by Django 4.2.11 on 2024-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0003_alter_cobranca_data_vencimento_alter_cobranca_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='uuid',
            field=models.CharField(),
        ),
    ]
