# Generated by Django 4.2.11 on 2024-03-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0004_alter_cobranca_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
