
services:
  db:
    image: postgres:16-alpine
    container_name: kanastra-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      POSTGRES_DB: kanastra_db
      POSTGRES_USER: kanastra_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_PORT: 5432

    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container
    healthcheck:                                           # ← adicionado
      test: ["CMD-SHELL", "pg_isready -U kanastra_user -d kanastra_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  web:
    image: back
    container_name: back
    build: 
      context: ../backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../backend/fintrack:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: kanastra_db
      DB_USER: kanastra_user
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    image: front
    container_name: front
    build: 
      context: ../frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ../frontend/front:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
    - REACT_APP_BACKEND_URL=http://localhost:8000/api

volumes:
  postgres_data:
