
services:
  db:
    image: postgres:16-alpine
    container_name: fintrack-db

    ##### Retirei o bind mount porque não funcionava no actions
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/

    environment:
      POSTGRES_DB: fintrack_db
      POSTGRES_USER: fintrack_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_PORT: 5432

    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container

  web:
    image: back
    container_name: back
    build: 
      context: ../backend
      dockerfile: Dockerfile.local

    ##### Retirei o bind mount porque não funcionava no actions
    # volumes:
    #   - ./backend/fintrack:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: fintrack_db
      DB_USER: fintrack_user
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    image: front
    container_name: front
    build: 
      context: ../frontend
      dockerfile: Dockerfile.local
    volumes:
      - ../frontend/front:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
