# Generated by Django 4.2.5 on 2026-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(fields=('user', 'filename'), name='unique_statement_per_user'),
        ),
    ]
