
name: Deploy Hosted Zone and ACM

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Escolha o ambiente (ex: dev, staging, prod)'
          required: true
          default: 'dev'
        password:
          description: 'Senha para rodar o workflow manualmente'
          required: true
          type: string

jobs:

  provision_https_dns:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Check password (for manual dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ "${{ github.event.inputs.password }}" != "${{ secrets.WORKFLOW_PASSWORD }}" ]; then
            echo "Senha incorreta!"
            exit 1
          fi
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init (ACM and Route 53)
        run: terraform init -var-file=dev.tfvars
        working-directory: ./terraform/${{ github.event.inputs.environment }}

      - name: Terraform Plan (ACM and Route 53)
        run: terraform plan -var-file=dev.tfvars -target=module.hosted_zone_acm
        working-directory: ./terraform/${{ github.event.inputs.environment }}

      - name: Terraform Apply (ACM and Route 53)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        run: terraform apply -auto-approve -var-file=dev.tfvars -target=module.hosted_zone_acm
        working-directory: ./terraform/${{ github.event.inputs.environment }}

   