name: Deploy Infrastructure with Terraform

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/dev


    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./terraform/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/dev

    - name: Terraform Apply
      if: github.ref == 'refs/heads/staging'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve
      working-directory: ./terraform/dev

  build_and_push:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push backend Docker image
      run: |
        docker buildx build --platform linux/amd64 -f ./backend/DockerfileProd \
        -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend:latest \
        --push ./backend

    - name: Build and push frontend Docker image
      run: |
        docker buildx build --platform linux/amd64 \
        --build-arg REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }} \
        -f ./frontend/DockerfileProd \
        -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend:latest \
        --push ./frontend
    
    # - name: Build and push database Docker image (if applicable)
    #   if: ${{ secrets.DB_IMAGE }} # Apenas inclua isso se você estiver gerando imagem do banco
    #   run: |
    #     docker buildx build --platform linux/amd64 \
    #     -f ./db/Dockerfile \
    #     -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/db:latest \
    #     --push ./db
