
name: Deploy Hosted Zone

on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Escolha o ambiente (ex: dev, staging, prod)'
          required: true
          default: 'dev'
        password:
          description: 'Senha para rodar o workflow manualmente'
          required: true
          type: string

jobs:

  provision_hosted_zone:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Check password (for manual dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ "${{ github.event.inputs.password }}" != "${{ secrets.WORKFLOW_PASSWORD }}" ]; then
            echo "Senha incorreta!"
            exit 1
          fi
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init (Hosted Zone)
        run: terraform init -var-file=dev.tfvars
        working-directory: ./terraform/${{ github.event.inputs.environment }}

      - name: Terraform Plan (Hosted Zone)
        run: |
          terraform plan \
            -var-file=dev.tfvars \
            -target=module.hosted_zone_acm.aws_route53_zone.my_zone \
            -target=module.hosted_zone_acm.aws_route53_record.frontend_www \
            -target=module.hosted_zone_acm.aws_route53_record.backend_api
        working-directory: ./terraform/${{ github.event.inputs.environment }}

      - name: Terraform Apply (Hosted Zone)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        run: |
          terraform apply \
            -auto-approve \
            -var-file=dev.tfvars \
            -target=module.hosted_zone_acm.aws_route53_zone.my_zone \
            -target=module.hosted_zone_acm.aws_route53_record.frontend_www \
            -target=module.hosted_zone_acm.aws_route53_record.backend_api
        working-directory: ./terraform/${{ github.event.inputs.environment }}

  print_terraform_outputs_and_state:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    needs: provision_hosted_zone
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init -var-file=dev.tfvars
        working-directory: ./terraform/${{ github.event.inputs.environment }}

      - name: Listar todos os outputs do Terraform
        run: terraform output
        working-directory: ./terraform/${{ github.event.inputs.environment }}

      - name: Imprimir estado completo do Terraform
        run: terraform show
        working-directory: ./terraform/${{ github.event.inputs.environment }}